name: Auditoría de Seguridad DevSecOps

# ¿Cuándo se ejecuta? Al hacer push a la rama main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajar tu código al servidor virtual
      - uses: actions/checkout@v3

      # 2. Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      # 3. Instalar herramientas de seguridad (Bandit)
      - name: Instalar Bandit (SAST)
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      # 4. EJECUTAR EL ESCANEO
      # -r: recursivo (busca en todas las carpetas)
      # -ll: nivel de severidad (busca cosas medias y altas)
      - name: Ejecutar Análisis Estático (Bandit)
        run: bandit -r . -ll -x venv


        